### ISSUE TITLE
循着论文而来....

### ISSUE THREAD

**Issue by Vickzhang** [hrlinlp/cepsum#1]
如题，啥时候能开放来学习

**Comment by pfllo** [comment]
+1 求数据集

**Comment by hrlinlp** [comment]
The dataset is going to be released in the few days. Sorry for the delay!

**Comment by chqiwang** [comment]
When the dataset will be released? Or any plan?

**Comment by hrlinlp** [comment]
Uploading now. However it really takes time for millions of pictures!

**Comment by liushuchun** [comment]
有人申请成功了吗？
