### ISSUE TITLE
Can you upload some sample data?

### ISSUE THREAD

**Issue by chqiwang** [hrlinlp/cepsum#2]

**Comment by hrlinlp** [comment]
Please fill out the application form and inform us the size of sample data you need.

**Comment by ruizewang** [comment]
Hello, thanks for your great work!
Could you upload few samples?  Just a few dozen will be fine.

**Comment by ruizewang** [comment]
> Please fill out the application form and inform us the size of sample data you need.

Hello, thanks for your great work!
Could you upload few samples? Just a few dozen will be fine.
